storage:
  type: sqlite
  path: /data/data.db

endpoints:
  - name: komodo
    group: core
    url: "https://komodo.kluhan.dev/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: fenrir
    group: hardware
    url: "https://fenrir.kluhan.dev/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: draugr
    group: hardware
    url: "https://draugr.kluhan.dev/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
